In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('nyt.csv', nrows=100)

In [3]:
df.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-01-01 00:57:55,2024-01-01 01:17:43,1.0,1.72,1.0,N,186,79,2,17.7,1.0,0.5,0.00,0.0,1.0,22.70,2.5,0.00
1,1,2024-01-01 00:03:00,2024-01-01 00:09:36,1.0,1.80,1.0,N,140,236,1,10.0,3.5,0.5,3.75,0.0,1.0,18.75,2.5,0.00
2,1,2024-01-01 00:17:06,2024-01-01 00:35:01,1.0,4.70,1.0,N,236,79,1,23.3,3.5,0.5,3.00,0.0,1.0,31.30,2.5,0.00
3,1,2024-01-01 00:36:38,2024-01-01 00:44:56,1.0,1.40,1.0,N,79,211,1,10.0,3.5,0.5,2.00,0.0,1.0,17.00,2.5,0.00
4,1,2024-01-01 00:46:51,2024-01-01 00:52:57,1.0,0.80,1.0,N,211,148,1,7.9,3.5,0.5,3.20,0.0,1.0,16.10,2.5,0.00
5,1,2024-01-01 00:54:08,2024-01-01 01:26:31,1.0,4.70,1.0,N,148,141,1,29.6,3.5,0.5,6.90,0.0,1.0,41.50,2.5,0.00
6,2,2024-01-01 00:49:44,2024-01-01 01:15:47,2.0,10.82,1.0,N,138,181,1,45.7,6.0,0.5,10.00,0.0,1.0,64.95,0.0,1.75
7,1,2024-01-01 00:30:40,2024-01-01 00:58:40,0.0,3.00,1.0,N,246,231,2,25.4,3.5,0.5,0.00,0.0,1.0,30.40,2.5,0.00
8,2,2024-01-01 00:26:01,2024-01-01 00:54:12,1.0,5.44,1.0,N,161,261,2,31.0,1.0,0.5,0.00,0.0,1.0,36.00,2.5,0.00
9,2,2024-01-01 00:28:08,2024-01-01 00:29:16,1.0,0.04,1.0,N,113,113,2,3.0,1.0,0.5,0.00,0.0,1.0,8.00,2.5,0.00

In [5]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data'))

CREATE TABLE "yellow_taxi_data" (
"VendorID" INTEGER,
  "tpep_pickup_datetime" TEXT,
  "tpep_dropoff_datetime" TEXT,
  "passenger_count" REAL,
  "trip_distance" REAL,
  "RatecodeID" REAL,
  "store_and_fwd_flag" TEXT,
  "PULocationID" INTEGER,
  "DOLocationID" INTEGER,
  "payment_type" INTEGER,
  "fare_amount" REAL,
  "extra" REAL,
  "mta_tax" REAL,
  "tip_amount" REAL,
  "tolls_amount" REAL,
  "improvement_surcharge" REAL,
  "total_amount" REAL,
  "congestion_surcharge" REAL,
  "Airport_fee" REAL
)

In [7]:
df.dtypes

VendorID                   int64
tpep_pickup_datetime      object
tpep_dropoff_datetime     object
passenger_count          float64
trip_distance            float64
RatecodeID               float64
store_and_fwd_flag        object
PULocationID               int64
DOLocationID               int64
payment_type               int64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
Airport_fee              float64
dtype: object

In [8]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

In [9]:
df.dtypes

VendorID                          int64
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int64
DOLocationID                      int64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
dtype: object

In [13]:
df.shape

(100, 19)

In [14]:
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
count,100.000000,100,100,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00,100.000000,100.000000,100.000000
mean,1.660000,2024-01-01 00:33:37.880000,2024-01-01 00:50:30.309999616,1.500000,3.342700,1.050000,166.370000,162.940000,1.280000,20.089000,1.877500,0.485000,3.303400,0.485800,0.98,28.790700,2.300000,0.087500
min,1.000000,2024-01-01 00:03:00,2024-01-01 00:09:33,0.000000,0.000000,1.000000,4.000000,4.000000,1.000000,-13.500000,-1.000000,-0.500000,0.000000,0.000000,-1.00,-18.500000,-2.500000,0.000000
25%,1.000000,2024-01-01 00:20:03,2024-01-01 00:34:24.750000128,1.000000,1.095000,1.000000,132.000000,107.000000,1.000000,9.300000,1.000000,0.500000,0.000000,0.000000,1.00,17.000000,2.500000,0.000000
50%,2.000000,2024-01-01 00:35:37.500000,2024-01-01 00:50:16,1.000000,1.910000,1.000000,161.000000,161.500000,1.000000,14.900000,1.000000,0.500000,3.000000,0.000000,1.00,23.040000,2.500000,0.000000
75%,2.000000,2024-01-01 00:46:24.750000128,2024-01-01 01:03:54.500000,2.000000,3.650000,1.000000,237.000000,236.000000,1.000000,25.750000,3.500000,0.500000,4.695000,0.000000,1.00,32.825000,2.500000,0.000000
max,2.000000,2024-01-01 00:58:18,2024-01-01 01:42:04,5.000000,23.900000,5.000000,263.000000,265.000000,4.000000,120.000000,6.000000,0.500000,14.150000,6.940000,1.00,127.940000,2.500000,1.750000
std,0.476095,NaN,NaN,0.915633,4.245318,0.411329,68.367937,70.543893,0.569955,17.983162,1.356101,0.111351,3.347568,1.779641,0.20,20.804689,0.768706,0.383325

In [15]:
df.isnull().sum()

VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
congestion_surcharge     0
Airport_fee              0
dtype: int64

In [16]:
df_describe = df.describe().round(3)
print (df_describe)

       VendorID           tpep_pickup_datetime          tpep_dropoff_datetime  \
count   100.000                            100                            100
mean      1.660     2024-01-01 00:33:37.880000  2024-01-01 00:50:30.309999616
min       1.000            2024-01-01 00:03:00            2024-01-01 00:09:33
25%       1.000            2024-01-01 00:20:03  2024-01-01 00:34:24.750000128
50%       2.000     2024-01-01 00:35:37.500000            2024-01-01 00:50:16
75%       2.000  2024-01-01 00:46:24.750000128     2024-01-01 01:03:54.500000
max       2.000            2024-01-01 00:58:18            2024-01-01 01:42:04
std       0.476                            NaN                            NaN

       passenger_count  trip_distance  RatecodeID  PULocationID  DOLocationID  \
count          100.000        100.000     100.000       100.000       100.000
mean             1.500          3.343       1.050       166.370       162.940
min              0.000          0.000       1.000         4.000         4.000
25%              1.000          1.095       1.000       132.000       107.000
50%              1.000          1.910       1.000       161.000       161.500
75%              2.000          3.650       1.000       237.000       236.000
max              5.000         23.900       5.000       263.000       265.000
std              0.916          4.245       0.411        68.368        70.544

       payment_type  fare_amount    extra  mta_tax  tip_amount  tolls_amount  \
count        100.00      100.000  100.000  100.000     100.000       100.000
mean           1.28       20.089    1.878    0.485       3.303         0.486
min            1.00      -13.500   -1.000   -0.500       0.000         0.000
25%            1.00        9.300    1.000    0.500       0.000         0.000
50%            1.00       14.900    1.000    0.500       3.000         0.000
75%            1.00       25.750    3.500    0.500       4.695         0.000
max            4.00      120.000    6.000    0.500      14.150         6.940
std            0.57       17.983    1.356    0.111       3.348         1.780

       improvement_surcharge  total_amount  congestion_surcharge  Airport_fee
count                 100.00       100.000               100.000      100.000
mean                    0.98        28.791                 2.300        0.088
min                    -1.00       -18.500                -2.500        0.000
25%                     1.00        17.000                 2.500        0.000
50%                     1.00        23.040                 2.500        0.000
75%                     1.00        32.825                 2.500        0.000
max                     1.00       127.940                 2.500        1.750
std                     0.20        20.805                 0.769        0.383